blank_issues_enabled: false
contact_links:
    - name: Community Support
      url: https://discord.gg/wn8pPVWD
      about: Please ask and answer questions here.
    - name: Heroku, Repl.it, Blocked site issues
      url: 
      about: Do not create issues for these.
